spring.application.name=DIMSUM

spring.datasource.url=jdbc:mysql://localhost:3306/DIMSUM
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.signerKey=uTDZ4amObo9fNJ1IHlGAuiOQiRxnThV4YOc/nH3rrEw6GNWOQSGSoZsdSiMoN5R1
jwt.expiration=3600